% f8
function val = f(v)
    val = (sin(v(:,2)) .* exp((1 - cos(v(:,1))).^2) + ...
        cos(v(:,1)) .* exp((1 - sin(v(:,2))).^2) + (v(:,1) - v(:,2)).^2) ...
        + (1/sign(sign(25 - (v(:,1) + 5).^2 - (v(:,2) + 5).^2)+1))' ;
end